import type { ActivityTemplate } from "@/types";

// ============================================================
// SAYES — UNIVERSAL ACTIVITY TEMPLATES
// Add a new activity type by adding one object here.
// The app never needs if/else per sport or hobby.
// ============================================================

export const ACTIVITY_TEMPLATES: ActivityTemplate[] = [
  // ── SPORTS ──────────────────────────────────────────────
  {
    id: "soccer",
    slug: "soccer",
    name: "Soccer / Football",
    emoji: "⚽",
    category: "SPORT",
    subcategory: "Team Sport",
    defaultDurationMin: 90,
    defaultMinParticipants: 10,
    defaultMaxParticipants: 22,
    supportsTeams: true,
    supportsTournament: true,
    fields: [
      { key: "format", label: "Format", type: "select", options: ["5v5", "7v7", "11v11", "Futsal"], required: false },
      { key: "surface", label: "Surface", type: "select", options: ["Grass", "Turf", "Indoor"], required: false },
    ],
  },
  {
    id: "hockey",
    slug: "hockey",
    name: "Hockey",
    emoji: "🏒",
    category: "SPORT",
    subcategory: "Team Sport",
    defaultDurationMin: 60,
    defaultMinParticipants: 6,
    defaultMaxParticipants: 20,
    supportsTeams: true,
    supportsTournament: true,
    fields: [
      { key: "type", label: "Type", type: "select", options: ["Ice", "Street", "Ball", "Roller"], required: false },
    ],
  },
  {
    id: "basketball",
    slug: "basketball",
    name: "Basketball",
    emoji: "🏀",
    category: "SPORT",
    subcategory: "Team Sport",
    defaultDurationMin: 60,
    defaultMinParticipants: 6,
    defaultMaxParticipants: 20,
    supportsTeams: true,
    supportsTournament: true,
    fields: [
      { key: "format", label: "Format", type: "select", options: ["3v3", "5v5", "Free play"], required: false },
    ],
  },
  {
    id: "tennis",
    slug: "tennis",
    name: "Tennis",
    emoji: "🎾",
    category: "SPORT",
    subcategory: "Racquet",
    defaultDurationMin: 60,
    defaultMinParticipants: 2,
    defaultMaxParticipants: 4,
    supportsTeams: false,
    supportsTournament: true,
    fields: [],
  },
  {
    id: "golf",
    slug: "golf",
    name: "Golf",
    emoji: "⛳",
    category: "SPORT",
    subcategory: "Individual",
    defaultDurationMin: 240,
    defaultMinParticipants: 1,
    defaultMaxParticipants: 4,
    supportsTeams: false,
    supportsTournament: true,
    fields: [
      { key: "holes", label: "Holes", type: "select", options: ["9", "18"], required: false },
    ],
  },
  {
    id: "volleyball",
    slug: "volleyball",
    name: "Volleyball",
    emoji: "🏐",
    category: "SPORT",
    subcategory: "Team Sport",
    defaultDurationMin: 60,
    defaultMinParticipants: 6,
    defaultMaxParticipants: 24,
    supportsTeams: true,
    supportsTournament: true,
    fields: [
      { key: "type", label: "Type", type: "select", options: ["Indoor", "Beach", "Park"], required: false },
    ],
  },
  {
    id: "badminton",
    slug: "badminton",
    name: "Badminton",
    emoji: "🏸",
    category: "SPORT",
    subcategory: "Racquet",
    defaultDurationMin: 60,
    defaultMinParticipants: 2,
    defaultMaxParticipants: 8,
    supportsTeams: false,
    supportsTournament: true,
    fields: [],
  },
  {
    id: "ski",
    slug: "ski",
    name: "Ski / Snowboard",
    emoji: "🎿",
    category: "SPORT",
    subcategory: "Winter",
    defaultDurationMin: 300,
    defaultMinParticipants: 2,
    defaultMaxParticipants: 20,
    supportsTeams: false,
    supportsTournament: false,
    fields: [
      { key: "discipline", label: "Discipline", type: "select", options: ["Ski", "Snowboard", "Both"], required: false },
    ],
  },
  {
    id: "skating",
    slug: "skating",
    name: "Patinage",
    emoji: "⛸️",
    category: "SPORT",
    subcategory: "Winter",
    defaultDurationMin: 90,
    defaultMinParticipants: 2,
    defaultMaxParticipants: 30,
    supportsTeams: false,
    supportsTournament: false,
    fields: [],
  },
  {
    id: "swimming",
    slug: "swimming",
    name: "Natation",
    emoji: "🏊",
    category: "SPORT",
    subcategory: "Aquatic",
    defaultDurationMin: 60,
    defaultMinParticipants: 2,
    defaultMaxParticipants: 20,
    supportsTeams: false,
    supportsTournament: true,
    fields: [],
  },
  {
    id: "cycling",
    slug: "cycling",
    name: "Vélo / Cyclisme",
    emoji: "🚴",
    category: "SPORT",
    subcategory: "Outdoor",
    defaultDurationMin: 120,
    defaultMinParticipants: 2,
    defaultMaxParticipants: 30,
    supportsTeams: false,
    supportsTournament: true,
    fields: [
      { key: "type", label: "Type", type: "select", options: ["Road", "Mountain", "City", "BMX"], required: false },
    ],
  },
  {
    id: "running",
    slug: "running",
    name: "Course à pied",
    emoji: "🏃",
    category: "SPORT",
    subcategory: "Outdoor",
    defaultDurationMin: 60,
    defaultMinParticipants: 2,
    defaultMaxParticipants: 100,
    supportsTeams: false,
    supportsTournament: true,
    fields: [
      { key: "distance", label: "Distance (km)", type: "number", required: false },
    ],
  },
  {
    id: "yoga",
    slug: "yoga",
    name: "Yoga",
    emoji: "🧘",
    category: "SPORT",
    subcategory: "Wellness",
    defaultDurationMin: 60,
    defaultMinParticipants: 2,
    defaultMaxParticipants: 20,
    supportsTeams: false,
    supportsTournament: false,
    fields: [
      { key: "style", label: "Style", type: "select", options: ["Hatha", "Vinyasa", "Bikram", "Yin", "Other"], required: false },
    ],
  },
  {
    id: "hiking",
    slug: "hiking",
    name: "Randonnée",
    emoji: "🥾",
    category: "NATURE",
    subcategory: "Outdoor",
    defaultDurationMin: 180,
    defaultMinParticipants: 2,
    defaultMaxParticipants: 30,
    supportsTeams: false,
    supportsTournament: false,
    fields: [
      { key: "distance", label: "Distance (km)", type: "number", required: false },
      { key: "difficulty", label: "Difficulté", type: "select", options: ["Facile", "Modéré", "Difficile", "Expert"], required: false },
    ],
  },

  // ── GAMES ────────────────────────────────────────────────
  {
    id: "treasure-hunt",
    slug: "treasure-hunt",
    name: "Chasse au trésor",
    emoji: "🗺️",
    category: "GAME",
    subcategory: "Urban Game",
    defaultDurationMin: 120,
    defaultMinParticipants: 4,
    defaultMaxParticipants: 40,
    supportsTeams: true,
    supportsTournament: false,
    fields: [
      { key: "steps", label: "Nombre d'étapes", type: "number", required: false },
      { key: "area", label: "Zone de jeu", type: "text", required: false },
    ],
  },
  {
    id: "photo-hunt",
    slug: "photo-hunt",
    name: "Chasse photo",
    emoji: "📸",
    category: "GAME",
    subcategory: "Urban Game",
    defaultDurationMin: 90,
    defaultMinParticipants: 4,
    defaultMaxParticipants: 30,
    supportsTeams: true,
    supportsTournament: false,
    fields: [],
  },
  {
    id: "board-game",
    slug: "board-game",
    name: "Jeux de société",
    emoji: "🧩",
    category: "GAME",
    subcategory: "Indoor",
    defaultDurationMin: 120,
    defaultMinParticipants: 2,
    defaultMaxParticipants: 12,
    supportsTeams: false,
    supportsTournament: true,
    fields: [
      { key: "gameName", label: "Jeu", type: "text", required: false },
    ],
  },
  {
    id: "video-game",
    slug: "video-game",
    name: "Jeux vidéo",
    emoji: "🎮",
    category: "GAME",
    subcategory: "Digital",
    defaultDurationMin: 120,
    defaultMinParticipants: 2,
    defaultMaxParticipants: 16,
    supportsTeams: true,
    supportsTournament: true,
    fields: [
      { key: "platform", label: "Plateforme", type: "select", options: ["PC", "PlayStation", "Xbox", "Nintendo", "Mobile"], required: false },
      { key: "game", label: "Jeu", type: "text", required: false },
    ],
  },

  // ── SOCIAL / ENTERTAINMENT ──────────────────────────────
  {
    id: "karaoke",
    slug: "karaoke",
    name: "Karaoké",
    emoji: "🎤",
    category: "SOCIAL",
    subcategory: "Entertainment",
    defaultDurationMin: 180,
    defaultMinParticipants: 4,
    defaultMaxParticipants: 30,
    supportsTeams: false,
    supportsTournament: true,
    fields: [],
  },
  {
    id: "cinema",
    slug: "cinema",
    name: "Cinéma",
    emoji: "🎬",
    category: "CULTURE",
    subcategory: "Entertainment",
    defaultDurationMin: 150,
    defaultMinParticipants: 2,
    defaultMaxParticipants: 20,
    supportsTeams: false,
    supportsTournament: false,
    fields: [
      { key: "movieTitle", label: "Film", type: "text", required: false },
    ],
  },
  {
    id: "dance",
    slug: "dance",
    name: "Danse",
    emoji: "💃",
    category: "CULTURE",
    subcategory: "Art",
    defaultDurationMin: 90,
    defaultMinParticipants: 4,
    defaultMaxParticipants: 30,
    supportsTeams: false,
    supportsTournament: false,
    fields: [
      { key: "style", label: "Style", type: "select", options: ["Salsa", "Bachata", "Hip-hop", "Swing", "Tango", "Contemporary", "Other"], required: false },
    ],
  },
  {
    id: "restaurant",
    slug: "restaurant",
    name: "Sortie restaurant",
    emoji: "🍽️",
    category: "FOOD_DRINK",
    subcategory: "Dining",
    defaultDurationMin: 120,
    defaultMinParticipants: 2,
    defaultMaxParticipants: 20,
    supportsTeams: false,
    supportsTournament: false,
    fields: [
      { key: "cuisineType", label: "Cuisine", type: "text", required: false },
    ],
  },
  {
    id: "bar",
    slug: "bar",
    name: "Bar / Bière",
    emoji: "🍺",
    category: "FOOD_DRINK",
    subcategory: "Nightlife",
    defaultDurationMin: 180,
    defaultMinParticipants: 2,
    defaultMaxParticipants: 30,
    supportsTeams: false,
    supportsTournament: false,
    fields: [],
  },
  {
    id: "cafe",
    slug: "cafe",
    name: "Café",
    emoji: "☕",
    category: "SOCIAL",
    subcategory: "Casual",
    defaultDurationMin: 90,
    defaultMinParticipants: 2,
    defaultMaxParticipants: 10,
    supportsTeams: false,
    supportsTournament: false,
    fields: [],
  },

  // ── HOBBIES / LEARNING ──────────────────────────────────
  {
    id: "language-exchange",
    slug: "language-exchange",
    name: "Échange linguistique",
    emoji: "🗣️",
    category: "LEARNING",
    subcategory: "Language",
    defaultDurationMin: 90,
    defaultMinParticipants: 2,
    defaultMaxParticipants: 12,
    supportsTeams: false,
    supportsTournament: false,
    fields: [
      { key: "language", label: "Langue", type: "text", required: true },
    ],
  },
  {
    id: "networking",
    slug: "networking",
    name: "Networking",
    emoji: "💼",
    category: "BUSINESS",
    subcategory: "Professional",
    defaultDurationMin: 120,
    defaultMinParticipants: 5,
    defaultMaxParticipants: 50,
    supportsTeams: false,
    supportsTournament: false,
    fields: [
      { key: "industry", label: "Secteur", type: "text", required: false },
    ],
  },
  {
    id: "party",
    slug: "party",
    name: "Fête / Soirée",
    emoji: "🎉",
    category: "SOCIAL",
    subcategory: "Party",
    defaultDurationMin: 240,
    defaultMinParticipants: 10,
    defaultMaxParticipants: 200,
    supportsTeams: false,
    supportsTournament: false,
    fields: [
      { key: "theme", label: "Thème", type: "text", required: false },
    ],
  },
  {
    id: "travel",
    slug: "travel",
    name: "Voyage / Sortie",
    emoji: "✈️",
    category: "TRAVEL",
    subcategory: "Adventure",
    defaultDurationMin: 480,
    defaultMinParticipants: 2,
    defaultMaxParticipants: 20,
    supportsTeams: false,
    supportsTournament: false,
    fields: [
      { key: "destination", label: "Destination", type: "text", required: true },
    ],
  },
  {
    id: "dating",
    slug: "dating",
    name: "Rencontre / Dating",
    emoji: "❤️",
    category: "SOCIAL",
    subcategory: "Dating",
    defaultDurationMin: 90,
    defaultMinParticipants: 2,
    defaultMaxParticipants: 2,
    supportsTeams: false,
    supportsTournament: false,
    fields: [],
  },
  {
    id: "friends",
    slug: "friends",
    name: "Trouver des amis",
    emoji: "👫",
    category: "SOCIAL",
    subcategory: "Friendship",
    defaultDurationMin: 120,
    defaultMinParticipants: 2,
    defaultMaxParticipants: 10,
    supportsTeams: false,
    supportsTournament: false,
    fields: [],
  },

  // ── CUSTOM — utilisateurs peuvent créer leurs propres types
  {
    id: "custom",
    slug: "custom",
    name: "Activité personnalisée",
    emoji: "⭐",
    category: "CUSTOM",
    defaultDurationMin: 60,
    defaultMinParticipants: 2,
    defaultMaxParticipants: 50,
    supportsTeams: false,
    supportsTournament: false,
    fields: [
      { key: "customType", label: "Type d'activité", type: "text", required: true },
    ],
  },
];

export const getTemplateBySlug = (slug: string): ActivityTemplate | undefined =>
  ACTIVITY_TEMPLATES.find((t) => t.slug === slug);

export const getTemplatesByCategory = (category: string) =>
  ACTIVITY_TEMPLATES.filter((t) => t.category === category);
